### ISSUE TITLE
THE REAL GAME

### ISSUE THREAD

**Issue by accessgames** [UnOriginal-Personal-Computer/website#1]
Gimme now or else olive ur adderss is 

**** SE Ta***r 

PLZ I DONt KNOW HOW 2 CODE I WONT DO ANYTHING BAD PLZPLZPLZPPLZ

**Comment by Quartinal** [comment]
Only in Texas you wouldn't know how to code ... Nah for real though

**Comment by Quartinal** [comment]
https://harvey.ai

**Comment by accessgames** [comment]
6029 SE Taylor Ct With the yellow house and the murphy construction van

**Comment by Quartinal** [comment]
🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏
